Repository LutheranWorldRelief/hummus, pull requests merged in 2019-12, with the labels that each got.

#363 Migration modular admin
  monitoring/forms.py
  monitoring/static/css/app.css
  monitoring/static/css/vendor.css
  monitoring/static/js/app.js
  monitoring/static/js/vendor.js
  monitoring/templates/modular_template/base.html
  monitoring/templates/modular_template/dashboard.html
  monitoring/templates/modular_template/header.html
  monitoring/templates/modular_template/helloworld.html
  monitoring/templates/modular_template/sidebar.html
  monitoring/views.py
Labels: migration

#371 Agregando bower al proyecto
  .gitignore
  bower.json
  hummus/settings.py
  monitoring/templates/modular_template/base.html
Labels: dependencies

#396 Implementado filtros dashboard
  bower.json
  monitoring/dashboard.py
  monitoring/jsonviews.py
  monitoring/static/js/dashboard-vue.js
  monitoring/static/js/mixins/graphic.js
  monitoring/templates/modular_template/dashboard.html
  monitoring/templates/modular_template/graphics.html
Labels: Bower
